### ISSUE TITLE
Caza mutante en make_dates_header

### ISSUE THREAD

**Issue by MaritzaB** [IslasGECI/datatools#5]
En la línea 23 sobrevive un mutante `-`
```
+ csv_data <- fread(csv, drop = c(1:4))
- csv_data <- fread(csv, drop = c(2:4))
```

**Comment by MaritzaB** [comment]
Holi  :v: @andrea-sanchez, me ayudarías a cazar este mutante :japanese_ogre: porfis?

**Comment by nepito** [comment]
@andrea-sanchez creo que ya no es necesario cazar ese mutante, creo que otro prueba que hicieron tú y @MaritzaB lo atrapó.
